[package]
name = "filter_ical"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking"] }
icalendar = "0.16.8"
regex = "1.10.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
