name: Deploy Filtered iCal

on:
  schedule:
    - cron: '0 * * * *'  # Run daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Release Binary
        run: |
          curl -L -o filter_ical https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/filter_ical
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Filter Script
        run: |
          filter_ical --args > filtered_calendar.ics

      - name: Upload Filtered iCal File
        uses: actions/upload-artifact@v3
        with:
          name: filtered-calendar
          path: filtered_calendar.ics
