name: Filter iCal

on:
  schedule:
    - cron: '0 * * * *'  # Run daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the project
        run: cargo build --release
  
      - name: Run Rust script to filter and update calendar
        run: cargo run --release

      - name: List files in directory
        run: ls -al

      - name: Checkout calendar branch
        uses: actions/checkout@v3
        with:
          ref: calendar 

      - name: List files in directory
        run: ls -al

      - name: Pull latest changes from calendar branch
        run: git pull --rebase origin calendar
  
      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add filtered_calendar.ics
          git commit -m "Update filtered calendar"
          git push origin calendar
